# Generated by Django 2.2.5 on 2019-09-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='profile_pics'),
        ),
    ]
