# Generated by Django 3.0.4 on 2020-03-14 16:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_auto_20200314_1741'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profili',
            new_name='Profile',
        ),
    ]
