# Generated by Django 3.0.4 on 2020-03-16 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200314_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kerkesat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emri', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('numri_tel', models.CharField(max_length=15)),
                ('profili', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
    ]
