# Generated by Django 3.0.4 on 2020-03-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200316_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kerkesat',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
