# Generated by Django 3.0.4 on 2020-03-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190918_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='short_description',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
