# Generated by Django 3.0.4 on 2020-03-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='allowed_memberships',
        ),
        migrations.RemoveField(
            model_name='course',
            name='ending_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='starting_date',
        ),
        migrations.AddField(
            model_name='course',
            name='imazhi_kursit',
            field=models.ImageField(default='default.jpg', upload_to='kurs_images'),
        ),
    ]
