# Generated by Django 3.0.4 on 2020-03-15 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0007_auto_20200315_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lendet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('titulli', models.CharField(max_length=30)),
                ('pershkrimi', models.TextField(max_length=400)),
                ('krijuar_me', models.DateTimeField(auto_now=True)),
                ('imazhi_lendes', models.ImageField(default='default.jpg', upload_to='kurs_images')),
                ('klasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Klasa')),
                ('krijues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Lendet'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
