# Generated by Django 3.0.4 on 2020-03-15 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20200315_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesimi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('titulli', models.CharField(max_length=30)),
                ('video_id', models.CharField(max_length=15)),
                ('pozicioni', models.IntegerField()),
                ('lenda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Lendet')),
            ],
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
