# Generated by Django 3.0.4 on 2020-03-15 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20200315_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesimi',
            name='lenda',
        ),
    ]
