# Generated by Django 3.0.4 on 2020-03-15 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_mesimi_lenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=30)),
                ('video_url', models.FileField(null=True, upload_to='videos/')),
                ('thumbnail', models.ImageField(upload_to='')),
                ('position', models.IntegerField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Lendet')),
            ],
        ),
        migrations.DeleteModel(
            name='Mesimi',
        ),
    ]
