# Generated by Django 3.0.4 on 2020-03-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20200315_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='course',
            new_name='lenda',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='position',
            new_name='pozicioni',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='title',
            new_name='titulli',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_id',
            field=models.CharField(default='', editable=False, max_length=11),
        ),
    ]
