# Generated by Django 3.0.4 on 2020-03-17 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20200315_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lendet'),
        ),
    ]
